# Generated by Django 5.0.6 on 2024-06-26 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarea', '0002_alter_tarea_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='completada',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterModelTable(
            name='tarea',
            table=None,
        ),
    ]
